name: Kernel
version: ${version}
main: com.lightre.kernel.Kernel
api-version: '1.21'
authors: [ Lightre ]
description: A core plugin providing essential commands and features for the server.
commands:
  kernel:
    description: Main command for the Kernel plugin.
    usage: /<command> [help|reload]
  heal:
    description: Heals a player to full health.
    usage: /<command> [player]
  feed:
    description: Fills a player's hunger bar to maximum.
    usage: /<command> [player]
  fly:
    description: Toggles flight mode.
    usage: /<command> [player]
  vanish:
    description: Toggles vanish mode.
    usage: /<command> [player]
  god:
    description: Toggles god mode.
    usage: /<command> [player]
  hat:
    description: Puts the item in your hand on your head.
    usage: /<command> [player]
    aliases: [ helmet ]
  whois:
    description: Displays detailed information about a player.
    usage: /<command> <player>
  broadcast:
    description: Sends a message to the entire server.
    usage: /<command> <message>
    aliases: [ bc ]
  adminchat:
    description: Sends a message to admin chat.
    usage: /<command> <message>
    aliases: [ ac ]
  freeze:
    description: Freezes a player, preventing all actions.
    usage: /<command> <player>
  clearchat:
    description: Clears chat for all players.
    usage: /<command>
    aliases: [ cc ]
  speed:
    description: Changes a player's walk or fly speed.
    usage: /<command> <walk|fly> <0-10> [player]