name: Build and Release to Modrinth

on:
  workflow_dispatch:

jobs:
  build_and_release:
    name: Build & Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Get project version from Gradle
        id: get_version
        run: echo "version=$(./gradlew -q printVersion)" >> $GITHUB_OUTPUT

      - name: Publish to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ${{ secrets.MODRINTH_PROJECT_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          name: "Kernel v${{ steps.get_version.outputs.version }}"

          version: ${{ steps.get_version.outputs.version }}

          files: "build/libs/*.jar"
          game-versions: ">=1.21"
          loaders: "spigot, paper"
          version-type: "release"